In [3]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv("/home/erick/Desktop/mcc20201/nnets/abalone.data", header = None)
df.head()

0      1      2      3       4       5       6      7   8
0  M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.150  15
1  M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.070   7
2  F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.210   9
3  M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.155  10
4  I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.055   7

In [67]:
y = df.iloc[0:,8]
df = df.drop([8], axis=1)
s = df.iloc[0:,0]
df = df.drop([0], axis = 1)

In [68]:
y.head()
y.unique()

array([15,  7,  9, 10,  8, 20, 16, 19, 14, 11, 12, 18, 13,  5,  4,  6, 21,
       17, 22,  1,  3, 26, 23, 29,  2, 27, 25, 24])

In [69]:
for i in range(4177):
    if y.iloc[i] in [1,2,3,4,5]:
        y.iloc[i] = 1
    if y.iloc[i] in [14,15]:
        y.iloc[i] = 2
    if y.iloc[i] in [16,17,18]:
        y.iloc[i] = 3
    if 18 < y.iloc[i]:
        y.iloc[i] = 4

In [70]:
y.head()
np.unique(y)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13])

In [71]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
enc.fit(y.values.reshape(-1,1))

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='ignore',
       n_values=None, sparse=True)

In [72]:
y_enc = enc.transform(y.values.reshape(-1,1)).toarray()
print(y_enc, len(y_enc))

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]] 4177


In [75]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
df.head()

1         2         3         4         5         6         7
0  0.513514  0.521008  0.084071  0.181335  0.150303  0.132324  0.147982
1  0.371622  0.352941  0.079646  0.079157  0.066241  0.063199  0.068261
2  0.614865  0.613445  0.119469  0.239065  0.171822  0.185648  0.207773
3  0.493243  0.521008  0.110619  0.182044  0.144250  0.149440  0.152965
4  0.344595  0.336134  0.070796  0.071897  0.059516  0.051350  0.053313

In [76]:
encs = OneHotEncoder(handle_unknown='ignore')
encs.fit(s.values.reshape(-1,1))
s_enc = encs.transform(s.values.reshape(-1,1)).toarray()
print(s_enc, len(s_enc))

[[0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]] 4177


In [78]:
data = np.concatenate((s_enc,df), axis=1)
data[0]
data = np.concatenate((data,y_enc), axis=1)
data[0]

array([0.        , 0.        , 1.        , 0.51351351, 0.5210084 ,
       0.0840708 , 0.18133522, 0.15030262, 0.1323239 , 0.14798206,
       0.        , 1.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [82]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(data, test_size=0.10, random_state=0)
np.savetxt("train_abalone.csv", train_data, delimiter=" ",  fmt='%f9')
np.savetxt("test_abalone.csv", test_data, delimiter=" ",  fmt='%f9')

In [80]:
len(data[0])

22